### PR TITLE
Dragging tags outside of component fixed

### LINKED ISSUE #15: Make it impossible to move text labels outside the frame of a component
This is an example of 3 text labels that have been moved outside the frame of the component.

image

Locations cannot be moved outside the frame and thus must contain code that detects when the frame edge is reached. Maybe this code can be refactored and moved to a super class of these two object.

### PR DESCRIPTION
**Pull request by Nielswps**
This makes sure that the tags for guards, selections, and so on are always snapped to a location inside the component, when they are dragged outside the component

### CODE REVIEW

File: src/main/java/dk/cs/aau/huppaal/presentations/TagPresentation.java [hunk 1]
```diff
@@ -212,6 +215,37 @@ private void initializeShape() {
                 textField.requestFocus(); // This needs to be done twice because of reasons
             }
 
+            //Handle constraints for guards, selects, synchronizations, and updates
+            if(getParent() instanceof NailPresentation){
+                if(getParent().localToParent(getBoundsInParent()).getCenterX() > getComponent().widthProperty().doubleValue() - textField.getWidth()) {
```
Comment (yrke) [inline src/main/java/dk/cs/aau/huppaal/presentations/TagPresentation.java]: It seems the two cases are very similar, I think there should be a function (or just extract the object that you work on)

somthing like: 
if (getParent() instanof NailPresentation) {
o = getParent() 
} else {
o = getParent.getParent()
}

if (o.localToParent(...
...

**Review by yrke — CHANGES_REQUESTED** [review]

File: src/main/java/dk/cs/aau/huppaal/presentations/TagPresentation.java (hunk 1 above)
Comment (Nielswps) [reply src/main/java/dk/cs/aau/huppaal/presentations/TagPresentation.java]: Definitely, must have missed it as I ran through it

**Review by yrke — APPROVED** [review]
